tls:
  certificates:
    - certFile: C:\etc\traefik\certs\_wildcard.basic-company-tds-consolidated.localhost.pem
      keyFile: C:\etc\traefik\certs\_wildcard.basic-company-tds-consolidated.localhost-key.pem